# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChuckNorris' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChuckNorris
  pod 'Alamofire', '~> 5.0.0-rc.3'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'NVActivityIndicatorView', '4.8.0'
  pod 'RealmSwift', '4.2.0'
  pod 'TagListView', '1.4.0'
  pod 'SwiftMessages', '6.0'

  target 'ChuckNorrisTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
